name: GA-DPH-Vaccine-Orders-List
on:
  schedule:
    # 0th minute every 2 hours
    - cron: '0 */2 * * *'
jobs:
  Run-R-Script:
    runs-on: macos-11.2
    r-version: 4.0.3
    steps:
      # this is a comment by the way, it won't hurt
      - name: clone-repo-from-triggering-branch
        uses: actions/checkout@v2

      - name: Set up R ${{r-version}}
        uses: r-lib/actions/setup-R@v1
        with:
          r-version: ${{r-version}}
        shell: bash

      - name: Install Dependencies
        run: |
          install.packages(c("tidyverse","pdftools","assertthat"))
        shell: Rscript {0}
